# Generated by Django 6.0 on 2025-12-30 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Jobs",
            new_name="Job",
        ),
    ]
